import styled from "styled-components";
export const StyledBotaoCadastrar = styled.button`
  box-sizing: border-box;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  padding: 0px 22px;
  gap: 10px;
  width: 259px;
  height: 38px;
  left: 0px;
  top: 0px;
  background: #868e96;
  border: 1px solid #868e96;
  border-radius: 4px;
  font-family: "Inter";
  font-style: normal;
  font-weight: 500;
  font-size: 12.8347px;
  line-height: 21px;
  color: #f8f9fa;
`;
